project_id = "mikipjdymkhocpjxsitd"

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.approve-user]
verify_jwt = false

[functions.auto-backup]
verify_jwt = false

[functions.auto-cancel-expired-bookings]
verify_jwt = false

[functions.booking-otp]
verify_jwt = false

[functions.cancel-registration]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.database-backup]
verify_jwt = false

[functions.database-restore]
verify_jwt = false

[functions.emergency-password-reset]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.restore-from-storage]
verify_jwt = false

[functions.send-announcement-notification]
verify_jwt = false

[functions.send-contact-form]
verify_jwt = false

[functions.send-event-reminders]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.setup-superadmin]
verify_jwt = false
